<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9upNBxf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9upNBxf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9upNBxf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9upNBxf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9upNBxf\App_KernelDevDebugContainer([
    'container.build_hash' => '9upNBxf',
    'container.build_id' => '73d53a9c',
    'container.build_time' => 1614779871,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9upNBxf');
