<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZsTrLjO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZsTrLjO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZsTrLjO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZsTrLjO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZsTrLjO\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZsTrLjO',
    'container.build_id' => '8dc82c09',
    'container.build_time' => 1614783554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZsTrLjO');
